{% set name = "twarc" %}
{% set version = "2.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/twarc-{{ version }}.tar.gz
  sha256: fa8ee3052d8b9678231bea95d1bdcbabb3968d35c56a8d1fcedc8982e8c66a66

build:
  entry_points:
    - twarc = twarc.command:main
    - twarc2 = twarc.command2:twarc2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.3
    - pytest-runner
    - pip
  run:
    - python >=3.3
    - click >=7,<9
    - click-config-file >=0.6
    - click-plugins >=1
    - humanize >=3.9
    - python-dateutil >=2.8
    - requests-oauthlib >=1.3
    - tqdm >=4.62

test:
  imports:
    - twarc
  commands:
    - pip check
    - twarc --help
    - twarc2 --help
  requires:
    - pip

about:
  home: https://github.com/docnow/twarc
  summary: Archive tweets from the command line
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
